AWSTemplateFormatVersion: 2010-09-09
Description: | 
  This CFN template was written for running Kittens Carousel webpage.
  
Resources: 
  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0bef6cc322bfff646
      InstanceType: t2.micro
      KeyName: thatsmykey
      SecurityGroupIds: 
        - sg-082f66f95b129f8be
      Tags: 
        - Key: Name
          Value: !Sub Web Server of ${AWS::StackName} Stack   
      UserData: 
       Fn::Base64:
        !Sub |
          #! /bin/bash
          yum update -y
          yum install httpd -y
          FOLDER="https://raw.githubusercontent.com/shequre/my_projects_aws14/main/101-kittens-carousel-static-website-ec2/static-web/"
          cd /var/www/html
          wget $FOLDER/index.html
          wget $FOLDER/cat0.jpg
          wget $FOLDER/cat1.jpg
          wget $FOLDER/cat2.jpg
          wget $FOLDER/cat3.png
          systemctl start httpd
          systemctl enable httpd
  WebServerSecuritygroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP for Apache Web Server
      GroupName: my_yirmiiki_seksen
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
                  

Outputs:
  WebsiteURL:
    Value: !Sub 
      - http://${PublicAddress}
      - PublicAddress: !GetAtt WebServerHost.PublicDnsName
    Description: Kittens Carousel Application URL